"""UPDATES THE SCHEMATICS OF THE DATABASE TABLES TO INCLUDE SOME MISSING COLUMNS SUCH AS PITCH_AUTHOR, DATE POSTED, AND USER BIO DATA

Revision ID: f55656d9a6b0
Revises: 6304d2009c67
Create Date: 2021-11-07 08:27:21.335025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f55656d9a6b0'
down_revision = '6304d2009c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date_posted', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'pitches', ['pitch_id'], ['pitch_id'])
    op.add_column('pitches', sa.Column('pitch_author', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('pitch_title', sa.String(length=350), nullable=True))
    op.add_column('pitches', sa.Column('pitch_category', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('date_published', sa.DateTime(), nullable=True))
    op.drop_constraint('pitches_comment_id_fkey', 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'comment_id')
    op.add_column('users', sa.Column('user_bio', sa.String(length=600), nullable=True))
    op.add_column('users', sa.Column('user_profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_profile_pic_path')
    op.drop_column('users', 'user_bio')
    op.add_column('pitches', sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitches_comment_id_fkey', 'pitches', 'comments', ['comment_id'], ['comment_id'])
    op.drop_column('pitches', 'date_published')
    op.drop_column('pitches', 'pitch_category')
    op.drop_column('pitches', 'pitch_title')
    op.drop_column('pitches', 'pitch_author')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'pitch_id')
    op.drop_column('comments', 'date_posted')
    # ### end Alembic commands ###
